// AUTO-GENERATED from the source Word document — verbatim legal text. Do not hand-edit prose.
export type LegalBlock = { type: "h" | "p" | "li"; text: string };

export const termsBlocks: LegalBlock[] = [
  { type: "p", text: "Last updated: June 2026." },
  { type: "p", text: "We, Halfcourt Global Pty Ltd ACN 698 923 689 (Halfcourt), registered office: 55 Collins Street, Melbourne VIC 3000, operate a website at www.playhalfcourt.com (Sites)." },
  { type: "p", text: "When we refer to Halfcourt we also refer to all companies within our company group, including all other related bodies corporate and subsidiaries." },
  { type: "p", text: "See also our Privacy Policy www.playhalfcourt.com/privacypolicy, and any applicable laws or regulations governing the purchase of products from us." },
  { type: "p", text: "If you access and use any part of the Sites on someone else's behalf, you represent that you have the authority to do so, and accept these Terms and Conditions (Terms), on their behalf." },
  { type: "h", text: "General" },
  { type: "p", text: "We may make changes to these Terms, or any content of the Sites, at any time, or upon notice as required by law. If we elect to modify these Terms, we will post a new version on the Sites and update the date set out above. Any changes are effective immediately upon posting to, or removal from, the Sites. Your continued use of the Sites thereafter constitutes your acceptance of any changes to the Sites or Terms. If you do not agree to any change, then you must immediately stop using the Sites." },
  { type: "p", text: "You should read and carefully consider these Terms before using the Sites, or otherwise placing an order online, and check back regularly for any changes. The terms that apply to your use of our Sites are the Terms that apply at the time you used the Sites." },
  { type: "h", text: "Using the Sites" },
  { type: "p", text: "The Sites are for your personal and non-commercial use only." },
  { type: "p", text: "You agree that you are solely responsible for all costs and expenses you may incur in relation to your use of the Sites." },
  { type: "p", text: "We make no promise that the Sites are appropriate or available for use in locations outside of Australia. If you choose to access the Sites from locations outside Australia, you acknowledge you do so at your own initiative and are responsible for compliance with local laws where they apply." },
  { type: "p", text: "You may use the Sites (and any products or services purchased on or via the Sites) for your own lawful, personal and non-commercial purposes only in accordance with these Terms. You must not:" },
  { type: "li", text: "modify, copy, distribute, transmit, display, perform, reproduce, publish, license, commercially exploit, create derivative works from, transfer, or sell any Content, software, products or services contained within, on or via the Sites;" },
  { type: "li", text: "use the Sites (and any products or services purchased on or via the Sites), or any of its Content, to further any commercial purpose, including, without limitation, any commercial activity, sales or offering for sale, advertising or advertising revenue generation activity on your own website, auction sites, group buying sites, social media sites or otherwise;" },
  { type: "li", text: "publish, distribute, transmit, sell, license or download the whole or any part of the Sites or any Content (except caching or as necessary to view the Sites);" },
  { type: "li", text: "use of the Sites or Content other than for personal use;" },
  { type: "li", text: "modify, reverse engineer or create any derivative works based upon the Sites or any Content (defined below);" },
  { type: "li", text: "collect account information for the benefit of yourself or another party;" },
  { type: "li", text: "use any meta tags or any other “hidden text” utilising any Content; or" },
  { type: "li", text: "use software robots, spiders, crawlers, or similar data gathering and extraction tools, or taking any other action that may impose an unreasonable burden or load on our infrastructure." },
  { type: "h", text: "Intellectual Property" },
  { type: "p", text: "In these Terms:" },
  { type: "li", text: "Content means any materials or content on the Sites or that contribute to the existence and the “look and feel” of the Sites, including information, graphics, headers, icons, images, logos, names, sounds, music, video, audio, text, software, HTML and code; and" },
  { type: "li", text: "Intellectual Property Rights includes patents, rights to inventions, copyright, trade marks, trade names and domain names, rights in goodwill, rights in confidential information and any other intellectual property rights, whether registered or unregistered and including all applications for, and renewals or extensions of, such rights and all similar rights which subsist now or in future anywhere in the world." },
  { type: "p", text: "The Sites and the Content (and all Intellectual Property Rights comprised therein) are owned by us, or in some cases, our affiliates, partners, related bodies corporate or licensors. The Intellectual Property Rights are protected by Australian and international laws." },
  { type: "p", text: "You are not granted any rights, including any Intellectual Property Rights, in relation to, or permitted to use, any part of the Content or the Sites, other than as expressly authorised by us, our third party licensors or applicable laws, such as the Copyright Act 1968 (Cth)." },
  { type: "p", text: "Any unauthorised publication, reproduction, exploitation, distribution, duplication, copying, including to another server or location, sale, access, modification or use of any part of the Sites or any Content is prohibited." },
  { type: "p", text: "Unless you have our prior written consent, you are expressly prohibited from:" },
  { type: "li", text: "using any automated process, software, or script to extract, scrape, crawl or collect data or Content in any manner, including but not limited to the use of web crawlers, bots, or spiders;" },
  { type: "li", text: "aggregating, collecting, or compiling Content for commercial or non-commercial purposes. This includes, but is not limited to, the use of Content to create databases, directories, or other aggregated content; and" },
  { type: "li", text: "using any artificial intelligence (AI) tools, machine learning algorithms, or other automated technologies to analyse, process, or generate content based on or through the use of the Content. This includes, but is not limited to, using the Content to (i) train AI models (ii) for any form of automated content generation and (iii) as input to an AI system, as a prompt, request, question, instruction or similar." },
  { type: "li", text: "By accessing and using this Site, you agree to comply with these restrictions. Any attempt to bypass these restrictions may result in legal action and/or termination of access to the Site." },
  { type: "h", text: "Prices and fees" },
  { type: "p", text: "Prices for our products are set out on our website. All prices are in Australian dollars and include GST at the applicable rate.." },
  { type: "h", text: "Providing information through the Sites" },
  { type: "p", text: "While we try to make sure that the Sites are secure, we do not actively monitor or check whether information supplied to us through the Sites is confidential, commercially sensitive or valuable." },
  { type: "p", text: "Other than any personal information which will be dealt with in accordance with our Privacy Policy www.playhalfcourt.com/privacypolicy, we do not guarantee that information supplied to us through the Sites will be kept confidential and we may use it on an unrestricted and free-of-charge basis as we reasonably see fit." },
  { type: "h", text: "Accuracy of information and availability of the Sites" },
  { type: "p", text: "We try to make sure that the Sites are accurate, up-to-date and free from bugs, but we cannot promise that it will be. Furthermore, we cannot promise that the Sites will be fit or suitable for any purpose. Any reliance that you may place on the information on the Sites is at your own risk." },
  { type: "p", text: "We may suspend or terminate access or operation of the Sites at any time as we see fit." },
  { type: "p", text: "Any Content is provided for your general information purposes only and to inform you about us and our products and news, features, services and other websites that may be of interest, but has not been tailored to your specific requirements or circumstances. It does not constitute technical, financial or legal advice or any other type of advice and should not be relied on for any purpose. You should always use your own independent judgment when using our Sites and their Content." },
  { type: "p", text: "While we try to make sure that the Sites are available for your use, we do not promise that the Sites will be available at all times or that your use of the Sites will be uninterrupted." },
  { type: "h", text: "Hyperlinks and third-party sites" },
  { type: "p", text: "The Sites may contain hyperlinks or references to third-party advertising and websites other than the Sites. Any such hyperlinks or references are provided for your convenience only. We have no control over third party advertising or websites and accept no legal responsibility for any content, material or information contained in them. The display of any hyperlink and reference to any third-party advertising or website does not mean that we endorse that third party’s website, products or services. Your use of a third-party site may be governed by the terms and conditions of that third-party site and is at your own risk." },
  { type: "h", text: "Our responsibility to you" },
  { type: "p", text: "If we breach these terms or are negligent, we are liable to you for foreseeable loss or damage that you suffer as a result. By “foreseeable” we mean that, at the time you accessed the Sites, it was either clear that such loss or damage would occur or you and we both knew that it might reasonably occur, as a result of something we did (or failed to do)." },
  { type: "p", text: "Nothing in these terms excludes or limits our liability for any death or personal injury caused by our negligence, liability for fraud or fraudulent misrepresentation, or any other liability that the law does not allow us to exclude or limit." },
  { type: "p", text: "To the fullest extent permitted by applicable law, neither we nor you will be liable for any indirect, special, punitive, incidental, or consequential damages of any kind, including loss of profits, loss of revenue, loss of data, or loss of goodwill, arising out of or in connection with the use of the Sites, whether in contract, tort (including negligence), or otherwise, even if the party had been advised of the possibility of such damages." },
  { type: "p", text: "Nothing in this clause excludes or limits liability to the extent prohibited by law, including liability for personal injury, death, or any other liability that cannot lawfully be excluded under applicable legislation." },
  { type: "p", text: "We are not liable to you if we fail to comply with these Terms because of circumstances beyond our reasonable control." },
  { type: "h", text: "No third-party rights" },
  { type: "p", text: "No one other than us or you has any right to enforce any of these terms." },
  { type: "h", text: "Termination" },
  { type: "p", text: "We may at any time and without notice to you:" },
  { type: "li", text: "temporarily suspend or disable the Sites; and" },
  { type: "li", text: "permanently cease operating the Sites." },
  { type: "h", text: "Transfer of rights" },
  { type: "p", text: "We may transfer our rights under these Terms to another business without your consent, but we will notify you of the transfer and make sure that your rights are not adversely affected as a result." },
  { type: "p", text: "You are not allowed to transfer your rights under these Terms to anyone without our prior written consent." },
  { type: "h", text: "Contacting us and complaints" },
  { type: "p", text: "If you are unhappy with the Sites, please contact us at team@playhalfcourt.com." },
  { type: "h", text: "Severability" },
  { type: "p", text: "Any part of these Terms that is illegal, void or unenforceable may be severed, and the remainder will continue in force." },
  { type: "h", text: "Governing law and jurisdiction" },
  { type: "p", text: "The laws of Victoria apply to these Terms." },
  { type: "p", text: "Any disputes will be subject to the non-exclusive jurisdiction of the courts of Victoria." },
];
