// AUTO-GENERATED from the source Word document — verbatim legal text. Do not hand-edit prose.
export type LegalBlock = { type: "h" | "p" | "li"; text: string };

export const privacyBlocks: LegalBlock[] = [
  { type: "h", text: "Halfcourt Global Pty Ltd commitment to privacy" },
  { type: "p", text: "Halfcourt Global Pty Ltd ACN 698 923 689, its subsidiaries and affiliates in Australia (collectively referred to as Halfcourt) are committed to managing personal information in accordance with the Australian Privacy Principles (APPs) under the Privacy Act 1988 (Cth) (Privacy Act) and in accordance with other applicable privacy laws." },
  { type: "p", text: "This document sets out our policies for managing your personal information and is referred to as our Privacy Policy." },
  { type: "p", text: "In this Privacy Policy, \"we\" and \"us\" refers to Halfcourt Global Pty Ltd and \"you\" refers to any individual about whom we collect personal information." },
  { type: "h", text: "About Halfcourt Global Pty Ltd" },
  { type: "p", text: "Halfcourt Global Pty Ltd is a sports technology and services company that operates a basketball-focused platform connecting players, venues and communities through games, programs, competitions and events." },
  { type: "p", text: "Halfcourt Global Pty Ltd offers a range of services including facilitating court bookings, organising and administering basketball runs, competitions and events, managing community participation, and partnering with venues to activate and optimise court usage." },
  { type: "p", text: "You may contact us for further information about Halfcourt Global Pty Ltd and any related entities that may be subject to this Privacy Policy." },
  { type: "h", text: "What Information Does Halfcourt Global Pty Ltd Collect About You?" },
  { type: "p", text: "Halfcourt Global Pty Ltd collects personal information about individuals who interact with its services, including users, participants, venue partners, and prospective clients." },
  { type: "p", text: "The types of personal information we collect will vary depending on the nature of your interaction with us, but generally fall within the categories outlined below." },
  { type: "h", text: "Users, Participants and Prospective Clients" },
  { type: "p", text: "When you register for, enquire about, or participate in our services, we collect personal information necessary to provide and manage those services." },
  { type: "p", text: "This may include:" },
  { type: "li", text: "your name, email address, phone number and other contact details;" },
  { type: "li", text: "account login details and profile information;" },
  { type: "li", text: "date of birth or age (where relevant to participation);" },
  { type: "li", text: "location information (such as suburb or preferred playing areas);" },
  { type: "li", text: "booking, participation and activity history;" },
  { type: "li", text: "payment and transaction information (processed via secure third-party providers);" },
  { type: "li", text: "preferences and interests relating to basketball activities and events; and" },
  { type: "li", text: "any additional personal information you provide to us, or authorise us to collect, as part of your interaction with Halfcourt Global Pty Ltd." },
  { type: "p", text: "Where you represent a venue, organisation or business that partners with Halfcourt Global Pty Ltd, we may collect:" },
  { type: "li", text: "your name, position and organisation details;" },
  { type: "li", text: "business contact information;" },
  { type: "li", text: "information relevant to venue operations, bookings and service delivery; and" },
  { type: "li", text: "communications and correspondence with us." },
  { type: "h", text: "Prospective employees/applicants" },
  { type: "p", text: "We collect personal information when recruiting personnel, such as your name, contact details, qualifications and work history. Generally, we will collect this information directly from you." },
  { type: "p", text: "We may also collect personal information from third parties in ways which you would expect (for example, from recruitment agencies or referees you have nominated). Before offering you a position, we may collect additional details such as your tax file number and superannuation information and other information necessary to conduct background checks to determine your suitability for certain positions (for example, positions which involve working with children)." },
  { type: "h", text: "Other individuals" },
  { type: "p", text: "Halfcourt Global Pty Ltd may collect personal information about other individuals who are not clients of Halfcourt Global Pty Ltd. This includes customers and members of the public who participate in events we are involved with; individual service providers and contractors to Halfcourt Global Pty Ltd; and other individuals who interact with Halfcourt Global Pty Ltd on a commercial basis. The types of personal information we collect depend on how you engage with Halfcourt Global Pty Ltd. Generally, this may include your name, contact details (such as phone number, email address, and postal address), and information relating to our interactions and transactions with you, including enquiries, service history, and payment details." },
  { type: "p", text: "If you are participating in an event we are managing or delivering, we may take images or audio-visual recordings which identify you." },
  { type: "p", text: "In limited circumstances, Halfcourt Global Pty Ltd may collect information which is considered sensitive information. For example, if you are injured at an event promoted or delivered by Halfcourt Global Pty Ltd we may collect health information about you in an emergency or otherwise with your consent." },
  { type: "p", text: "We may collect personal information about children (for example, when children participate in events we are involved with). Where children do not have sufficient maturity and understanding to make decisions about their personal information, we will require their parents or guardians to make decisions on their behalf." },
  { type: "p", text: "You can always decline to give Halfcourt Global Pty Ltd any personal information we request, but that may mean we cannot provide you with some or all of the services you have requested. If you have any concerns about personal information we have requested, please let us know." },
  { type: "h", text: "Visitors to our websites" },
  { type: "p", text: "The way in which we handle the personal information of visitors to our websites is discussed below." },
  { type: "h", text: "How and why does Halfcourt Global Pty Ltd collect and use your personal information?" },
  { type: "p", text: "Halfcourt Global Pty Ltd collects personal information that is reasonably necessary to carry out its business functions and activities, including to assess and manage user needs and to provide its basketball, venue activation and related platform services." },
  { type: "p", text: "We may also collect and use personal information for administrative and operational purposes, including billing, account management, entering into contracts, and maintaining our relationships with users, venue partners and other stakeholders." },
  { type: "p", text: "The purposes for which Halfcourt Global Pty Ltd collects and uses personal information depend on the nature of your interaction with us, but generally include:" },
  { type: "li", text: "responding to enquiries, requests for information and customer support;" },
  { type: "li", text: "facilitating registrations, bookings, participation in programs, competitions, events and community activities;" },
  { type: "li", text: "managing, planning, promoting and administering our services, programs and events;" },
  { type: "li", text: "communicating with you about your account, bookings, updates and relevant promotions (in accordance with applicable laws);" },
  { type: "li", text: "managing relationships with venue operators, partners and service providers;" },
  { type: "li", text: "processing payments and maintaining financial and transactional records;" },
  { type: "li", text: "conducting research, analytics and service improvement activities;" },
  { type: "li", text: "developing, enhancing and marketing our services and user experience;" },
  { type: "li", text: "recruitment and engagement processes (including employees, contractors and volunteers); and" },
  { type: "li", text: "responding to complaints and complying with legal and regulatory obligations." },
  { type: "p", text: "Halfcourt Global Pty Ltd generally collects personal information directly from you. This may occur when you interact with us via our platform, website, mobile applications, social media, over the phone, by email, or in person." },
  { type: "p", text: "We may also collect personal information from third parties where it is unreasonable or impracticable to collect it directly from you, or where you have consented. These third parties may include:" },
  { type: "li", text: "venue partners, event organisers or affiliated entities;" },
  { type: "li", text: "payment processors and booking platforms;" },
  { type: "li", text: "third-party service providers who support our operations (such as IT, data hosting and marketing providers); and" },
  { type: "li", text: "publicly available sources." },
  { type: "p", text: "Halfcourt Global Pty Ltd may also collect and use personal information for market research, analytics and innovation purposes to improve and develop our products, services and user experience" },
  { type: "h", text: "Does Halfcourt Global Pty Ltd use automated decision making?" },
  { type: "p", text: "Halfcourt Global Pty Ltd may use automated processes to assist in delivering its services and improving user experience. This may include the use of personal information such as account details, activity history, location data and user preferences." },
  { type: "p", text: "Automated or partially automated processes may be used for purposes such as:" },
  { type: "li", text: "matching users with games, events or venues;" },
  { type: "li", text: "recommending programs, competitions or content;" },
  { type: "li", text: "managing bookings and scheduling;" },
  { type: "li", text: "detecting fraudulent or suspicious activity; and" },
  { type: "li", text: "personalising communications and user experience." },
  { type: "p", text: "These processes may involve the use of algorithms or computer programs that analyse personal information to support operational decisions. However, Halfcourt Global Pty Ltd does not generally make decisions that have a significant legal or similarly significant effect on individuals solely by automated means without human involvement." },
  { type: "h", text: "How does Halfcourt Global Pty Ltd interact with you via the internet?" },
  { type: "p", text: "You may visit our websites www.playhalfcourt.com without identifying yourself. If you identify yourself (for example, by providing your contact details in an enquiry), any personal information you provide to Halfcourt Global Pty Ltd will be managed in accordance with this Privacy Policy." },
  { type: "p", text: "Halfcourt Global Pty Ltd's websites use cookies. A “cookie” is a small file stored on your computer's browser, which assists in managing customised settings of the website and delivering content. We collect certain information such as your device type, browser type, IP address, pages you have accessed on our websites and on third-party websites. You are not identifiable from such information." },
  { type: "p", text: "You can use the settings in your browser to control how your browser deals with cookies. However, in doing so, you may be unable to access certain pages or content on our website." },
  { type: "p", text: "Halfcourt Global Pty Ltd's websites may contain links to third-party websites. Halfcourt Global Pty Ltd is not responsible for the content or privacy practices of websites that are linked to our website." },
  { type: "h", text: "Can you deal with Halfcourt Global Pty Ltd anonymously?" },
  { type: "p", text: "Halfcourt Global Pty Ltd will provide individuals with the opportunity of remaining anonymous or using a pseudonym in their dealings with us where it is lawful and practicable (for example, when making a general enquiry). Generally, it is not practicable for Halfcourt Global Pty Ltd to deal with individuals anonymously or pseudonymously on an ongoing basis. If we do not collect personal information about you, you may be unable to utilise our services or participate in our events, programs or activities we manage or deliver." },
  { type: "h", text: "How does Halfcourt Global Pty Ltd hold information?" },
  { type: "p", text: "Halfcourt Global Pty Ltd stores information in paper-based files or other electronic record keeping methods in secure databases (including trusted third-party storage providers based in Australia and overseas). Personal information may be collected in paper-based documents and converted to electronic form for use or storage (with the original paper-based documents either archived or securely destroyed). We take reasonable steps to protect your personal information from misuse, interference and loss and from unauthorised access, modification or disclosure" },
  { type: "p", text: "Halfcourt Global Pty Ltd maintains physical security over paper and electronic data stores, such as through locks and security systems at our premises. We also maintain computer and network security, for example, we use firewalls (security measures for the Internet) and other security systems such as user identifiers and passwords to control access to our computer systems." },
  { type: "p", text: "Our websites do not necessarily use encryption or other technologies to ensure the secure transmission of information via the internet. Users of our websites are encouraged to exercise care in sending personal information via the internet." },
  { type: "p", text: "We take steps to destroy or de-identify information that we no longer require." },
  { type: "h", text: "Does Halfcourt Global Pty Ltd use or disclose your personal information for direct marketing?" },
  { type: "p", text: "Halfcourt Global Pty Ltd may use or disclose your personal information for the purpose of informing you about our services, upcoming promotions and events, or other opportunities that may interest you. If you do not want to receive direct marketing communications, you can opt-out at any time by contacting us using the contact details below." },
  { type: "p", text: "If you opt-out of receiving marketing material from us, Halfcourt Global Pty Ltd may still contact you in relation to its ongoing relationship with you." },
  { type: "h", text: "How does Halfcourt Global Pty Ltd use and disclose personal information?" },
  { type: "p", text: "Halfcourt Global Pty Ltd collects, holds, uses and discloses personal information for purposes permitted under the Australian Privacy Principles, including where such use or disclosure is reasonably necessary for, or directly related to, its functions and activities." },
  { type: "p", text: "Halfcourt Global Pty Ltd primarily uses personal information for the primary purpose for which it was collected, and for secondary purposes where permitted under the APPs, including where the individual would reasonably expect such use or disclosure. These purposes include:" },
  { type: "li", text: "providing, administering and improving its services, platform, programs, competitions and events;" },
  { type: "li", text: "facilitating user registrations, bookings, participation and engagement in basketball activities and related services;" },
  { type: "li", text: "communicating with individuals in relation to their account, transactions, service updates and relevant marketing (in accordance with applicable laws);" },
  { type: "li", text: "managing relationships with venue operators, partners and service providers;" },
  { type: "li", text: "processing payments, maintaining records and undertaking administrative and operational functions;" },
  { type: "li", text: "undertaking data analysis, research, product development and service enhancement; and" },
  { type: "li", text: "complying with legal, regulatory and reporting obligations." },
  { type: "p", text: "Halfcourt Global Pty Ltd may disclose personal information for these purposes to:" },
  { type: "li", text: "third party service providers (including IT, cloud storage, data hosting, payment processors and marketing platforms), some of which may be located overseas;" },
  { type: "li", text: "venue operators, partners and event organisers to enable the delivery of services and participation in activities;" },
  { type: "li", text: "professional advisers, including legal, accounting and insurance providers;" },
  { type: "li", text: "government agencies, regulatory bodies or law enforcement authorities where required or authorised by law; and" },
  { type: "li", text: "other persons or entities where the individual has consented to the disclosure or where disclosure is otherwise permitted under the APPs." },
  { type: "p", text: "Where Halfcourt Global Pty Ltd discloses personal information to overseas recipients, it will take reasonable steps to ensure that the recipient does not breach the Australian Privacy Principles iHn relation to that information, unless an exception under the Privacy Act 1988 (Cth) applies." },
  { type: "p", text: "Halfcourt Global Pty Ltd takes reasonable steps to ensure that personal information it discloses is accurate, up-to-date and complete, and that recipients are subject to appropriate obligations of confidentiality and privacy." },
  { type: "h", text: "For clients" },
  { type: "p", text: "The purposes for which we may use and disclose your personal information will depend on the services we are providing you. For example, if you have engaged us to deliver a service, we may disclose information about you to service providers where this is relevant to our services." },
  { type: "h", text: "For customers and participants" },
  { type: "p", text: "If you are a customer or participant in an event, we may disclose your personal information to our clients and venues where this is reasonably necessary for, and relevant to, the delivery of the event. We may use images or audio-visual recordings which identify you for promotional purposes where you would reasonably expect this to occur." },
  { type: "h", text: "Disclosure to contractors and other service providers" },
  { type: "p", text: "Halfcourt Global Pty Ltd may disclose information to third parties we engage in order to provide our services, including contractors and service providers used for data processing, data analysis, customer satisfaction surveys, information technology services and support, website maintenance/development, printing, archiving, mail-outs, and market research." },
  { type: "p", text: "Personal information may also be shared between related and affiliated companies of Halfcourt Global Pty Ltd, located in Australia and overseas." },
  { type: "p", text: "Third parties to whom we have disclosed your personal information may contact you directly to let you know they have collected your personal information and to give you information about their privacy policies." },
  { type: "h", text: "Use and disclosure for administration and management" },
  { type: "p", text: "Halfcourt Global Pty Ltd will also use and disclose personal information for a range of administrative, management and operational purposes. This includes:" },
  { type: "li", text: "administering billing and payments and debt recovery;" },
  { type: "li", text: "planning, managing, monitoring and evaluating our services;" },
  { type: "li", text: "quality improvement activities;" },
  { type: "li", text: "statistical analysis and reporting;" },
  { type: "li", text: "training staff, contractors and other workers;" },
  { type: "li", text: "risk management and management of legal liabilities and claims (for example, liaising with insurers and legal representatives);" },
  { type: "li", text: "responding to enquiries and complaints regarding our services;" },
  { type: "li", text: "obtaining advice from consultants and other professional advisers; and" },
  { type: "li", text: "responding to subpoenas and other legal orders and obligations." },
  { type: "h", text: "Other uses and disclosures" },
  { type: "p", text: "We may use and disclose your personal information for other purposes explained at the time of collection or otherwise as set out in this Privacy Policy." },
  { type: "h", text: "Does Halfcourt Global Pty Ltd disclose your personal information overseas?" },
  { type: "p", text: "Halfcourt Global Pty Ltd is a global organisation and works with clients, service providers, sponsors and commercial interests across the globe. It is likely that your personal information will be disclosed to overseas recipients." },
  { type: "p", text: "Unless we have your consent, or an exception under the APPs applies, we will only disclose your personal information to overseas recipients where we have taken reasonable steps to ensure that the overseas recipient does not breach the APPs in relation to your personal information." },
  { type: "p", text: "Entities which are related entities of Halfcourt Global Pty Ltd, or are otherwise affiliated with Halfcourt Global Pty Ltd, have operations in New Zealand, United States of America, United Kingdom and Philippines. In circumstances where your information is disclosed to overseas recipients, those recipients are likely to be located in countries in the regions in which Halfcourt Global Pty Ltd and its related entities and affiliates operate." },
  { type: "h", text: "How can you access or seek correction of your personal information?" },
  { type: "p", text: "You are entitled to access your personal information held by Halfcourt Global Pty Ltd on request. To request access to your personal information please contact our Privacy Officer using the contact details set out below." },
  { type: "p", text: "You will not be charged for making a request to access your personal information but you may be charged for the reasonable time and expense incurred in compiling information in response to your request." },
  { type: "p", text: "We will take reasonable steps to ensure that the personal information we collect, use or disclose is accurate, complete and up-to-date. You can help us to do this by letting us know if you notice errors or discrepancies in information we hold about you and letting us know if your personal details change." },
  { type: "p", text: "However, if you consider any personal information we hold about you is inaccurate, out-of-date, incomplete, irrelevant or misleading you are entitled to request correction of the information. After receiving a request from you, we will take reasonable steps to correct your information." },
  { type: "p", text: "We may decline your request to access or correct your personal information in certain circumstances in accordance with the APPs. If we do refuse your request, we will provide you with a reason for our decision and, in the case of a request for correction, we will include a statement with your personal information about the requested correction." },
  { type: "h", text: "What should you do if you have a complaint about the handling of your personal information?" },
  { type: "p", text: "You may contact Halfcourt Global Pty Ltd at any time if you have any questions or concerns about this Privacy Policy or about the way in which your personal information has been handled." },
  { type: "p", text: "You may make a complaint about privacy to the Privacy Officer at the contact details set out below." },
  { type: "p", text: "The Privacy Officer will first consider your complaint to determine whether there are simple or immediate steps which can be taken to resolve the complaint. We will generally respond to your complaint within a week." },
  { type: "p", text: "If your complaint requires more detailed consideration or investigation, we will acknowledge receipt of your complaint within a week and endeavour to complete our investigation into your complaint promptly. We may ask you to provide further information about your complaint and the outcome you are seeking. We will then typically gather relevant facts, locate and review relevant documents and speak with individuals involved." },
  { type: "p", text: "In most cases, we will investigate and respond to a complaint within 30 days of receipt of the complaint. If the matter is more complex or our investigation may take longer, we will let you know." },
  { type: "p", text: "If you are not satisfied with our response to your complaint, or you consider that Halfcourt Global Pty Ltd may have breached the APPs or the Privacy Act, a complaint may be made to the Office of the Australian Information Commissioner (OAIC). The OAIC can be contacted by telephone on 1300 363 992 or by using the contact details on the OAIC website." },
  { type: "h", text: "How are changes made to this privacy policy?" },
  { type: "p", text: "Halfcourt Global Pty Ltd may amend this Privacy Policy from time to time, with or without notice to you. We recommend that you visit our website regularly to keep up to date with any changes." },
  { type: "h", text: "How can you contact Halfcourt Global Pty Ltd?" },
  { type: "p", text: "The contact details for Halfcourt Global Pty Ltd are:" },
  { type: "p", text: "Halfcourt Global Pty Ltd Privacy Officer" },
  { type: "p", text: "Address: 55 Collins Street, Melbourne VIC 3000" },
  { type: "p", text: "Email address: team@playhalfcourt.com" },
  { type: "p", text: "This Privacy Policy was last updated in June 2026." },
];
